services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      SESSION_SECRET: "dev-secret-key-change-in-production-abcdef123456"
      NODE_ENV: development
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./database:/app/database
